In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("../data/bestsellers with categories.csv")
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 30.2 KB

In [4]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df = df.drop("Name", axis=1)

In [7]:
X = df.drop("Genre", axis=1)
y = df["Genre"]

In [8]:
X.head()

                     Author  User Rating  Reviews  Price  Year
0                  JJ Smith          4.7    17350      8  2016
1              Stephen King          4.6     2052     22  2011
2        Jordan B. Peterson          4.7    18979     15  2018
3             George Orwell          4.7    21424      6  2017
4  National Geographic Kids          4.8     7665     12  2019

In [9]:
y.head()

0    Non Fiction
1        Fiction
2    Non Fiction
3        Fiction
4    Non Fiction
Name: Genre, dtype: str

In [10]:
df.shape

(550, 6)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [12]:
print(X_train.shape)
print(X_test.shape)

(440, 5)
(110, 5)

In [14]:
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

In [15]:
author_train = encoder.fit_transform(X_train[["Author"]])

In [16]:
author_test = encoder.transform(X_test[["Author"]])

In [17]:
print(author_train.shape)
print(author_test.shape)

(440, 222)
(110, 222)

In [18]:
numerical_cols = ["User Rating", "Reviews", "Price", "Year"]

In [19]:
scaler = StandardScaler()
numerical_train = scaler.fit_transform(X_train[numerical_cols])
numerical_test = scaler.transform(X_test[numerical_cols])

In [20]:
print(numerical_train.shape)
print(numerical_test.shape)

(440, 4)
(110, 4)

In [21]:
X_train_final = np.hstack((author_train, numerical_train))
X_test_final = np.hstack((author_test, numerical_test))

In [22]:
print(X_train_final.shape)
print(X_test_final.shape)

(440, 226)
(110, 226)

In [23]:
numerical_train.mean(axis=0)

array([ 1.45035499e-15,  8.07434927e-18, -4.03717464e-17, -5.25640137e-15])

In [24]:
numerical_train.std(axis=0)

array([1., 1., 1., 1.])

In [ ]:
## Completed preprocessing